# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/universal7880-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7880-common/proprietary/app/FFFFFFFF000000000000000000000001.drbin:vendor/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:vendor/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:vendor/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000001f.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000001f.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000038.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:vendor/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:vendor/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000014.tlbin:vendor/app/mcRegistry/ffffffffd00000000000000000000014.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000017.tlbin:vendor/app/mcRegistry/ffffffffd00000000000000000000017.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001b.tlbin:vendor/app/mcRegistry/fffffffff0000000000000000000001b.tlbin \
    vendor/samsung/universal7880-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:vendor/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/universal7880-common/proprietary/bin/gpsd:vendor/bin/gpsd \
    vendor/samsung/universal7880-common/proprietary/vendor/bin/mcDriverDaemon:vendor/bin/mcDriverDaemon \
    vendor/samsung/universal7880-common/proprietary/bin/sensorhubservice:vendor/bin/sensorhubservice \
    vendor/samsung/universal7880-common/proprietary/bin/wcnss_filter:vendor/bin/wcnss_filter \
    vendor/samsung/universal7880-common/proprietary/etc/Tfa9896.cnt:vendor/etc/Tfa9896.cnt \
    vendor/samsung/universal7880-common/proprietary/etc/ca.pem:vendor/etc/ca.pem \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/Data.msc:vendor/etc/firmware/Data.msc \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/bdwlan30.bin:vendor/etc/firmware/bdwlan30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/bdwlan32.bin:vendor/etc/firmware/bdwlan32.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv.bin:vendor/etc/firmware/nvm_tlv.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv_1.3.bin:vendor/etc/firmware/nvm_tlv_1.3.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv_2.1.bin:vendor/etc/firmware/nvm_tlv_2.1.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv_3.0.bin:vendor/etc/firmware/nvm_tlv_3.0.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv_3.2.bin:vendor/etc/firmware/nvm_tlv_3.2.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/nvm_tlv_tf_1.1.bin:vendor/etc/firmware/nvm_tlv_tf_1.1.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/otp30.bin:vendor/etc/firmware/otp30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/qwlan30.bin:vendor/etc/firmware/qwlan30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/qwlan30_ibss.bin:vendor/etc/firmware/qwlan30_ibss.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv.img:vendor/etc/firmware/rampatch_tlv.img \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:vendor/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:vendor/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:vendor/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:vendor/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/rampatch_tlv_tf_1.1.tlv:vendor/etc/firmware/rampatch_tlv_tf_1.1.tlv \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/utf30.bin:vendor/etc/firmware/utf30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/utfbd30.bin:vendor/etc/firmware/utfbd30.bin \
    vendor/samsung/universal7880-common/proprietary/etc/firmware/utfbd32.bin:vendor/etc/firmware/utfbd32.bin \
    vendor/samsung/universal7880-common/proprietary/etc/nfc/sec_s3nrn81_rfreg.bin:vendor/etc/nfc/sec_s3nrn81_rfreg.bin \
    vendor/samsung/universal7880-common/proprietary/lib/hw/camera.vendor.exynos5.so:vendor/lib/hw/camera.vendor.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/hw/gralloc.exynos5.so:vendor/lib/hw/gralloc.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/hw/hwcomposer.exynos5.so:vendor/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib/libExynosHWCService.so:vendor/lib/libExynosHWCService.so \
    vendor/samsung/universal7880-common/proprietary/lib/libExynosOMX_Core.so:vendor/lib/libExynosOMX_Core.so \
    vendor/samsung/universal7880-common/proprietary/lib/libExynosOMX_Resourcemanager.so:vendor/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynoscamera.so:vendor/lib/libexynoscamera.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynoscamera3.so:vendor/lib/libexynoscamera3.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosdisplay.so:vendor/lib/libexynosdisplay.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosgscaler.so:vendor/lib/libexynosgscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib/libexynosscaler.so:vendor/lib/libexynosscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib/libfloatingfeature.so:vendor/lib/libfloatingfeature.so \
    vendor/samsung/universal7880-common/proprietary/lib/libhdmi.so:vendor/lib/libhdmi.so \
    vendor/samsung/universal7880-common/proprietary/lib/libhwcutils.so:vendor/lib/libhwcutils.so \
    vendor/samsung/universal7880-common/proprietary/lib/libhwjpeg.so:vendor/lib/libhwjpeg.so \
    vendor/samsung/universal7880-common/proprietary/lib/libprotobuf-cpp-fulN.so:vendor/lib/libprotobuf-cpp-fulN.so \
    vendor/samsung/universal7880-common/proprietary/lib/libprotobuf-cpp-litN.so:vendor/lib/libprotobuf-cpp-litN.so \
    vendor/samsung/universal7880-common/proprietary/lib/libsensorlistener.so:vendor/lib/libsensorlistener.so \
    vendor/samsung/universal7880-common/proprietary/lib/libstagefrighthw.so:vendor/lib/libstagefrighthw.so \
    vendor/samsung/universal7880-common/proprietary/lib/libtfa98xx.so:vendor/lib/libtfa98xx.so \
    vendor/samsung/universal7880-common/proprietary/lib/libuniapi.so:vendor/lib/libuniapi.so \
    vendor/samsung/universal7880-common/proprietary/lib/libuniplugin.so:vendor/lib/libuniplugin.so \
    vendor/samsung/universal7880-common/proprietary/lib/libvirtualdisplay.so:vendor/lib/libvirtualdisplay.so \
    vendor/samsung/universal7880-common/proprietary/lib/libwrappergps.so:vendor/lib/libwrappergps.so \
    vendor/samsung/universal7880-common/proprietary/lib/modules/qca_cld/qca_cld_wlan.ko:vendor/lib/modules/qca_cld/qca_cld_wlan.ko \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:vendor/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:vendor/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:vendor/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:vendor/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:vendor/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:vendor/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:vendor/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:vendor/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:vendor/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:vendor/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/camera.vendor.exynos5.so:vendor/lib64/hw/camera.vendor.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/gps.default.so:vendor/lib64/hw/gps.default.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/gralloc.exynos5.so:vendor/lib64/hw/gralloc.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/hwcomposer.exynos5.so:vendor/lib64/hw/hwcomposer.exynos5.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/sensorhubs.universal7880.so:vendor/lib64/hw/sensorhubs.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/lib64/hw/sensors.universal7880.so:vendor/lib64/hw/sensors.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libExynosHWCService.so:vendor/lib64/libExynosHWCService.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libExynosOMX_Core.so:vendor/lib64/libExynosOMX_Core.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libExynosOMX_Resourcemanager.so:vendor/lib64/libExynosOMX_Resourcemanager.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libbauthserver.so:vendor/lib64/libbauthserver.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libbauthtzcommon.so:vendor/lib64/libbauthtzcommon.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libegis_fp_normal_sensor_test.so:vendor/lib64/libegis_fp_normal_sensor_test.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynoscamera.so:vendor/lib64/libexynoscamera.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynoscamera3.so:vendor/lib64/libexynoscamera3.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosdisplay.so:vendor/lib64/libexynosdisplay.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosgscaler.so:vendor/lib64/libexynosgscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libexynosscaler.so:vendor/lib64/libexynosscaler.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libfloatingfeature.so:vendor/lib64/libfloatingfeature.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libhdmi.so:vendor/lib64/libhdmi.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libhwcutils.so:vendor/lib64/libhwcutils.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libhwjpeg.so:vendor/lib64/libhwjpeg.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libprotobuf-cpp-fulN.so:vendor/lib64/libprotobuf-cpp-fulN.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libprotobuf-cpp-litN.so:vendor/lib64/libprotobuf-cpp-litN.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libsensorhub.so:vendor/lib64/libsensorhub.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libsensorhubservice.so:vendor/lib64/libsensorhubservice.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libsensorlistener.so:vendor/lib64/libsensorlistener.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libstagefrighthw.so:vendor/lib64/libstagefrighthw.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libsynaFpSensorTestNwd.so:vendor/lib64/libsynaFpSensorTestNwd.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libuniapi.so:vendor/lib64/libuniapi.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libuniplugin.so:vendor/lib64/libuniplugin.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libvirtualdisplay.so:vendor/lib64/libvirtualdisplay.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libwrappergps.so:vendor/lib64/libwrappergps.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Decoder.so:vendor/lib64/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:vendor/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:vendor/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:vendor/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so:vendor/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so:vendor/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Decoder.so:vendor/lib64/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Encoder.so:vendor/lib64/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:vendor/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/lib64/omx/libOMX.Exynos.WMV.Decoder.so:vendor/lib64/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/fimc_is_lib.bin:vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/mfc_fw.bin:vendor/firmware/mfc_fw.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/nfc/sec_s3nrn81_firmware.bin:vendor/firmware/nfc/sec_s3nrn81_firmware.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/setfile_3p8.bin:vendor/firmware/setfile_3p8.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/firmware/setfile_3p8_front.bin:vendor/firmware/setfile_3p8_front.bin \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/egl/libGLES_mali.so:vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/hw/memtrack.universal7880.so:vendor/lib/hw/memtrack.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/hw/nfc_nci.default.so:vendor/lib/hw/nfc_nci.default.so \
    vendor/samsung/universal7880-common/proprietary/lib/libMcClient.so:vendor/lib/libMcClient.so \
    vendor/samsung/universal7880-common/proprietary/lib/libMcRegistry.so:vendor/lib/libMcRegistry.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libcsc.so:vendor/lib/libcsc.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libexynosutils.so:vendor/lib/libexynosutils.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libexynosv4l2.so:vendor/lib/libexynosv4l2.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libhwc2on1adapter.so:vendor/lib/libhwc2on1adapter.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libion_exynos.so:vendor/lib/libion_exynos.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/libmpp.so:vendor/lib/libmpp.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/egl/libGLES_mali.so:vendor/lib64/egl/libGLES_mali.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/hw/memtrack.universal7880.so:vendor/lib64/hw/memtrack.universal7880.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/hw/nfc_nci.default.so:vendor/lib64/hw/nfc_nci.default.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libMcClient.so:vendor/lib64/libMcClient.so \
    vendor/samsung/universal7880-common/proprietary/lib64/libMcRegistry.so:vendor/lib64/libMcRegistry.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libcsc.so:vendor/lib64/libcsc.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libexynosutils.so:vendor/lib64/libexynosutils.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libexynosv4l2.so:vendor/lib64/libexynosv4l2.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libhwc2on1adapter.so:vendor/lib64/libhwc2on1adapter.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libion_exynos.so:vendor/lib64/libion_exynos.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/libmpp.so:vendor/lib64/libmpp.so \
    vendor/samsung/universal7880-common/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:vendor/lib64/mediadrm/libdrmclearkeyplugin.so

ifeq ($(WITH_EXYNOS_BSP),)
endif

# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali

# Qualcomm WiFi driver
PRODUCT_PACKAGES += qca_cld_wlan
